name: Debug Third-Party Action

on:
  push:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test a non-AWS action
        uses: peter-evans/is-core-changed@v3