name: Debug Network and Resolution

on:
  push:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Test network connectivity to GitHub
        run: curl -v https://api.github.com

      - name: 2. Test action resolution
        uses: actions/checkout@v4