name: Debug Action Resolution

on:
  push:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test Checkout Action
        uses: actions/checkout@v4

      - name: Test ECR Login Action
        uses: aws-actions/login-ecr@v1